sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
  - '4'
before_script:
  - 'if [ -n "${ESLINT-}" ]; then npm install --no-save "eslint@${ESLINT}"; fi'
  - npm ls > /dev/null
script:
  - 'if [ -n "${LINTONLY-}" ]; then npm run lint; else npm run cover && npm run check-coverage; fi'
after_success:
  - npm run travis-after-all
env:
  matrix:
   - ESLINT=5
   - ESLINT=4
   - ESLINT=3
matrix:
  include:
    - node_js: "node"
      env: LINTONLY=true
  exclude:
    - node_js: "4"
      env: ESLINT=5
